# constants_ngos.py

NGOS = [
    {"ngo_id": "NGO001", "ngo_name": "Gawad Kalinga", "category": "Poverty Alleviation", "region_focus": "Nationwide"},
    {"ngo_id": "NGO002", "ngo_name": "Philippine Red Cross", "category": "Disaster Relief", "region_focus": "Nationwide"},
    {"ngo_id": "NGO003", "ngo_name": "Roots of Health", "category": "Health", "region_focus": "Palawan"},
    {"ngo_id": "NGO004", "ngo_name": "Likhaan", "category": "Women’s Health", "region_focus": "NCR & Luzon"},
    {"ngo_id": "NGO005", "ngo_name": "Nutrition Foundation of the Philippines", "category": "Nutrition", "region_focus": "Nationwide"},
    {"ngo_id": "NGO006", "ngo_name": "Haribon Foundation", "category": "Environment", "region_focus": "Nationwide"},
    {"ngo_id": "NGO007", "ngo_name": "Tambuyog Development Center", "category": "Fisheries & Livelihoods", "region_focus": "Coastal Luzon"},
    {"ngo_id": "NGO008", "ngo_name": "Legal Rights and Natural Resources Center", "category": "Rights & Environment", "region_focus": "Nationwide"},
    {"ngo_id": "NGO009", "ngo_name": "Social Weather Stations (SWS)", "category": "Research & Data", "region_focus": "Nationwide"},
    {"ngo_id": "NGO010", "ngo_name": "Fairplay for All Foundation", "category": "Education & Poverty", "region_focus": "NCR (Payatas)"},
    {"ngo_id": "NGO011", "ngo_name": "Caritas Manila", "category": "Poverty & Education", "region_focus": "NCR"},
    {"ngo_id": "NGO012", "ngo_name": "Save Philippine Seas", "category": "Marine Conservation", "region_focus": "Nationwide"},
    {"ngo_id": "NGO013", "ngo_name": "Childhope Philippines", "category": "Street Children", "region_focus": "NCR"},
    {"ngo_id": "NGO014", "ngo_name": "Hands On Manila", "category": "Volunteerism", "region_focus": "NCR"},
    {"ngo_id": "NGO015", "ngo_name": "Philippine Animal Welfare Society (PAWS)", "category": "Animal Welfare", "region_focus": "Nationwide"},
    {"ngo_id": "NGO016", "ngo_name": "Tahanan ng Pagmamahal", "category": "Orphan Care", "region_focus": "NCR"},
    {"ngo_id": "NGO017", "ngo_name": "Kythe Foundation", "category": "Pediatric Health", "region_focus": "Nationwide"},
    {"ngo_id": "NGO018", "ngo_name": "Teach for the Philippines", "category": "Education", "region_focus": "Nationwide"},
    {"ngo_id": "NGO019", "ngo_name": "World Wide Fund for Nature Philippines (WWF-PH)", "category": "Environment", "region_focus": "Nationwide"},
    {"ngo_id": "NGO020", "ngo_name": "Human Rights Watch Philippines", "category": "Human Rights", "region_focus": "Nationwide"},
    {"ngo_id": "NGO021", "ngo_name": "Love Yourself PH", "category": "HIV/AIDS Awareness", "region_focus": "NCR"},
    {"ngo_id": "NGO022", "ngo_name": "Angat Buhay", "category": "Community Development", "region_focus": "Nationwide"},
    {"ngo_id": "NGO023", "ngo_name": "iVolunteer Philippines", "category": "Volunteerism", "region_focus": "Nationwide"},
    {"ngo_id": "NGO024", "ngo_name": "Strays Worth Saving", "category": "Animal Rescue", "region_focus": "Nationwide"},
    {"ngo_id": "NGO025", "ngo_name": "Tahanan ng Pagmamahal Children’s Home", "category": "Orphan Care", "region_focus": "NCR"},
    {"ngo_id": "NGO026", "ngo_name": "PAWSsion Project", "category": "Animal Rescue", "region_focus": "Nationwide"},
    {"ngo_id": "NGO027", "ngo_name": "Disaster Response Philippines", "category": "Disaster Relief", "region_focus": "Nationwide"},
    {"ngo_id": "NGO028", "ngo_name": "Habitat for Humanity Philippines", "category": "Housing", "region_focus": "Nationwide"},
    {"ngo_id": "NGO029", "ngo_name": "Save the Children Philippines", "category": "Child Welfare", "region_focus": "Nationwide"},
    {"ngo_id": "NGO030", "ngo_name": "SOS Children’s Villages Philippines", "category": "Orphan & Family Care", "region_focus": "Nationwide"},
]
